#!/bin/bash
tool_name="$(basename "$0")"
uv --quiet --directory "../project-mcp-tools" run cli --target-project "../super-fruit-world" "$tool_name" "$@" | jq -r '(. as $in | try (.data | fromjson) catch $in.data)'
